[build]
target = "thumbv4t-none-eabi" # Specify the cpu / system architecture we are targeting

[unstable]
build-std = ["core"] # Specify we only want core

[target.thumbv4t-none-eabi]
runner = "/Applications/mGBA.app/Contents/MacOS/mGBA"
rustflags = [
    "-Clinker=arm-none-eabi-ld", # uses the ARM linker
    "-Clink-arg=-Tlinker.ld", # sets the link script
]
